version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ".:/usr/src/app"
            - "./_docker/nginx/conf.d:/etc/nginx/conf.d"
        ports:
            - "8080:80"
        depends_on:
            - php
        container_name: svfcode_test-nginx
    php:
        build:
            context: .
            dockerfile: ./_docker/Dockerfile
        container_name: svfcode_test-php
        volumes:
            - ".:/usr/src/app"

